# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(312321)
$foreground = rgb(FDF2E8)
$color0 = rgb(584846)
$color1 = rgb(803B43)
$color2 = rgb(7F6965)
$color3 = rgb(836D67)
$color4 = rgb(838E92)
$color5 = rgb(B89F8B)
$color6 = rgb(BCA38D)
$color7 = rgb(F4E3D5)
$color8 = rgb(AB9F95)
$color9 = rgb(AB4F5A)
$color10 = rgb(AA8C86)
$color11 = rgb(AF9189)
$color12 = rgb(AFBEC2)
$color13 = rgb(F6D4B9)
$color14 = rgb(FBD9BC)
$color15 = rgb(F4E3D5)
